### ISSUE TITLE
Hitting the memory limit on M5 Stack

### ISSUE THREAD

**Issue by sukeshak** [finger563/esp32-wireless-display#3]
LD build/ESP32_Wireless_Display.elf
d:/msys32/opt/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: D:/ProjectX2018/ESP32_Wireless_Display/src/build/ESP32_Wireless_Display.elf section `.dram0.bss' will not fit in region `dram0_0_seg'

d:/msys32/opt/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: region `dram0_0_seg' **overflowed by 5800 bytes**

Can you suggest what can be done? :(
I think the WROVER KIT has more memory..

**Comment by finger563** [comment]
I think the main way to reduce code-size is to swap out the font files or remove characters you don't need.  Right now it has [an 8x12 pixel character font](https://github.com/finger563/esp32-wireless-display/blob/master/src/components/Fonts/Fonts.cpp#L449) as well as a [5x7 pixel character font](https://github.com/finger563/esp32-wireless-display/blob/master/src/components/Fonts/Fonts.cpp#L330) so you could remove the `5x7` size font, since only the `8x12` is [used here](https://github.com/finger563/esp32-wireless-display/blob/master/src/components/DisplayTask/DisplayTask.cpp#L188) (or you could remove the `8x12` and use the `5x7` which is smaller).

**Comment by sukeshak** [comment]
First of all, your code is the best structured sample I found for ESP32, very well segregated in different relevant folders. Thank you for the code sample 👍 
There is something wrong after the latest ESP-IDF update I believe.
For testing, I removed all the content from font.cpp and also disabled Draw_8x12_string to avoid further compile errors.

Still the result is 
**region `dram0_0_seg' overflowed by 4776 bytes**

For another sample program I tested, it showed lack of space and I just changed from 2MB to 4MB in menuconfig and it successfully compiled and flashed (+worked). Thus I think there is something weird about the lack of space errors. 

Also I don't see your code taking that much space, does it?

**Comment by finger563** [comment]
Thanks :)

Ah - I should have suggested checking the config for your platform - you're right the code doesn't take much space, I had just assumed you were using a variant that had very little RAM. Have you tried updating the config for this codebase?

**Comment by sukeshak** [comment]
I am using M5Stack for this prototype. What kind of config change do you suggest?
http://www.m5stack.com/

**Comment by finger563** [comment]
closing; archiving this repo in favor of the newer https://github.com/esp-cpp/wireless-debug-display
